version: 2

jobs:
    build:
        macos:
            xcode: "9.3.0"
        shell: /bin/bash --login -o pipefail
        steps:
            - checkout

            - restore_cache:
                key: "v1-gems"
            - run:
                name: Install with bundler
                command: bundle check || bundle install --path .bundle
            - save_cache:
                key: "v1-gems"
                paths: ["./.bundle"]

            - run:
                name: Run tests
                command: set -o pipefail && xcodebuild build test -workspace Toshi.xcworkspace -scheme "Tests" -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty --color && exit ${PIPESTATUS[0]}

            - run:
                name: Danger
                command: bundle exec danger

