version: 2

jobs:
    build-and-test:
        macos:
            xcode: "9.3.0"
        # Use custom shell per https://circleci.com/docs/2.0/testing-ios/#using-custom-versions-of-cocoapods-and-other-ruby-gems
        shell: /bin/bash --login -eo pipefail
        steps:
            - checkout
            - run:
                name: Install with bundler
                command: bundle install
            - run:
                name: Run tests with Fastlane
                command: bundle exec fastlane ci_test
            - run:
                name: Danger
                command: bundle exec danger

workflows:
  version: 2
  build-and-test:
      jobs:
          - build-and-test
